// Zepp OS Watchface generated by AI WatchFace Creator (V2 Format)
// V2 Manifest: Full A OD support with dynamic widgets
// Compatible with Amazfit Balance 2, Balance, Active Max
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('WatchFaceEditor');
        
        // Sensor for weather and system info
        let weatherSensor = null;
        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // Initialize sensors
                try {
                    weatherSensor = hmSensor.createSensor(hmSensor.id.WEATHER);
                } catch (e) {
                    logger.log('Weather sensor init failed:', e);
                }
                
                // ========== NORMAL MODE BACKGROUND ==========
                let widget_1 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: px(0),
                    y: px(0),
                    w: px(480),
                    h: px(480),
                    src: 'background.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== NORMAL MODE WIDGETS ==========

                // IMG_DATE - IMG_DATE Widget
                let widget_2 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: px(222),
                    day_startY: px(118.37200396170354),
                    day_sc_array: ['date_digit_main_0o4qpxxqtznd_0.png', 'date_digit_main_0o4qpxxqtznd_1.png', 'date_digit_main_0o4qpxxqtznd_2.png', 'date_digit_main_0o4qpxxqtznd_3.png', 'date_digit_main_0o4qpxxqtznd_4.png', 'date_digit_main_0o4qpxxqtznd_5.png', 'date_digit_main_0o4qpxxqtznd_6.png', 'date_digit_main_0o4qpxxqtznd_7.png', 'date_digit_main_0o4qpxxqtznd_8.png', 'date_digit_main_0o4qpxxqtznd_9.png'],
                    day_tc_array: ['date_digit_main_0o4qpxxqtznd_0.png', 'date_digit_main_0o4qpxxqtznd_1.png', 'date_digit_main_0o4qpxxqtznd_2.png', 'date_digit_main_0o4qpxxqtznd_3.png', 'date_digit_main_0o4qpxxqtznd_4.png', 'date_digit_main_0o4qpxxqtznd_5.png', 'date_digit_main_0o4qpxxqtznd_6.png', 'date_digit_main_0o4qpxxqtznd_7.png', 'date_digit_main_0o4qpxxqtznd_8.png', 'date_digit_main_0o4qpxxqtznd_9.png'],
                    day_en_array: ['date_digit_main_0o4qpxxqtznd_0.png', 'date_digit_main_0o4qpxxqtznd_1.png', 'date_digit_main_0o4qpxxqtznd_2.png', 'date_digit_main_0o4qpxxqtznd_3.png', 'date_digit_main_0o4qpxxqtznd_4.png', 'date_digit_main_0o4qpxxqtznd_5.png', 'date_digit_main_0o4qpxxqtznd_6.png', 'date_digit_main_0o4qpxxqtznd_7.png', 'date_digit_main_0o4qpxxqtznd_8.png', 'date_digit_main_0o4qpxxqtznd_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // IMG_DATE - IMG_DATE Widget
                let widget_3 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: px(223),
                    day_startY: px(118.37200396170354),
                    day_sc_array: ['date_digit_main_biwt670bks7_0.png', 'date_digit_main_biwt670bks7_1.png', 'date_digit_main_biwt670bks7_2.png', 'date_digit_main_biwt670bks7_3.png', 'date_digit_main_biwt670bks7_4.png', 'date_digit_main_biwt670bks7_5.png', 'date_digit_main_biwt670bks7_6.png', 'date_digit_main_biwt670bks7_7.png', 'date_digit_main_biwt670bks7_8.png', 'date_digit_main_biwt670bks7_9.png'],
                    day_tc_array: ['date_digit_main_biwt670bks7_0.png', 'date_digit_main_biwt670bks7_1.png', 'date_digit_main_biwt670bks7_2.png', 'date_digit_main_biwt670bks7_3.png', 'date_digit_main_biwt670bks7_4.png', 'date_digit_main_biwt670bks7_5.png', 'date_digit_main_biwt670bks7_6.png', 'date_digit_main_biwt670bks7_7.png', 'date_digit_main_biwt670bks7_8.png', 'date_digit_main_biwt670bks7_9.png'],
                    day_en_array: ['date_digit_main_biwt670bks7_0.png', 'date_digit_main_biwt670bks7_1.png', 'date_digit_main_biwt670bks7_2.png', 'date_digit_main_biwt670bks7_3.png', 'date_digit_main_biwt670bks7_4.png', 'date_digit_main_biwt670bks7_5.png', 'date_digit_main_biwt670bks7_6.png', 'date_digit_main_biwt670bks7_7.png', 'date_digit_main_biwt670bks7_8.png', 'date_digit_main_biwt670bks7_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // IMG_DATE - IMG_DATE Month Widget
                let widget_4 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    month_startX: px(274.21866952789696),
                    month_startY: px(130.7027731924728),
                    month_sc_array: ['month_main_hkap2qmwbjr_0.png', 'month_main_hkap2qmwbjr_1.png', 'month_main_hkap2qmwbjr_2.png', 'month_main_hkap2qmwbjr_3.png', 'month_main_hkap2qmwbjr_4.png', 'month_main_hkap2qmwbjr_5.png', 'month_main_hkap2qmwbjr_6.png', 'month_main_hkap2qmwbjr_7.png', 'month_main_hkap2qmwbjr_8.png', 'month_main_hkap2qmwbjr_9.png', 'month_main_hkap2qmwbjr_10.png', 'month_main_hkap2qmwbjr_11.png'],
                    month_tc_array: ['month_main_hkap2qmwbjr_0.png', 'month_main_hkap2qmwbjr_1.png', 'month_main_hkap2qmwbjr_2.png', 'month_main_hkap2qmwbjr_3.png', 'month_main_hkap2qmwbjr_4.png', 'month_main_hkap2qmwbjr_5.png', 'month_main_hkap2qmwbjr_6.png', 'month_main_hkap2qmwbjr_7.png', 'month_main_hkap2qmwbjr_8.png', 'month_main_hkap2qmwbjr_9.png', 'month_main_hkap2qmwbjr_10.png', 'month_main_hkap2qmwbjr_11.png'],
                    month_en_array: ['month_main_hkap2qmwbjr_0.png', 'month_main_hkap2qmwbjr_1.png', 'month_main_hkap2qmwbjr_2.png', 'month_main_hkap2qmwbjr_3.png', 'month_main_hkap2qmwbjr_4.png', 'month_main_hkap2qmwbjr_5.png', 'month_main_hkap2qmwbjr_6.png', 'month_main_hkap2qmwbjr_7.png', 'month_main_hkap2qmwbjr_8.png', 'month_main_hkap2qmwbjr_9.png', 'month_main_hkap2qmwbjr_10.png', 'month_main_hkap2qmwbjr_11.png'],
                    month_zero: 0,
                    month_space: 0,
                    month_is_character: true,
                    month_align: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // IMG_DATE - IMG_WEEK Widget
                let widget_5 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                    x: px(137.1917464509739),
                    y: px(132.93738857708814),
                    week_en: ['week_main_0jsjisxv1nvn_0.png', 'week_main_0jsjisxv1nvn_1.png', 'week_main_0jsjisxv1nvn_2.png', 'week_main_0jsjisxv1nvn_3.png', 'week_main_0jsjisxv1nvn_4.png', 'week_main_0jsjisxv1nvn_5.png', 'week_main_0jsjisxv1nvn_6.png'],
                    week_sc: ['week_main_0jsjisxv1nvn_0.png', 'week_main_0jsjisxv1nvn_1.png', 'week_main_0jsjisxv1nvn_2.png', 'week_main_0jsjisxv1nvn_3.png', 'week_main_0jsjisxv1nvn_4.png', 'week_main_0jsjisxv1nvn_5.png', 'week_main_0jsjisxv1nvn_6.png'],
                    week_tc: ['week_main_0jsjisxv1nvn_0.png', 'week_main_0jsjisxv1nvn_1.png', 'week_main_0jsjisxv1nvn_2.png', 'week_main_0jsjisxv1nvn_3.png', 'week_main_0jsjisxv1nvn_4.png', 'week_main_0jsjisxv1nvn_5.png', 'week_main_0jsjisxv1nvn_6.png'],
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Heart - TEXT_IMG Widget
                let widget_6 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: px(68.22223506107625),
                    y: px(222.61046550016505),
                    w: px(95.79399141630901),
                    h: px(51.50214592274678),
                    font_array: ['heart_digit_main_gziiiigq1xo_0.png', 'heart_digit_main_gziiiigq1xo_1.png', 'heart_digit_main_gziiiigq1xo_2.png', 'heart_digit_main_gziiiigq1xo_3.png', 'heart_digit_main_gziiiigq1xo_4.png', 'heart_digit_main_gziiiigq1xo_5.png', 'heart_digit_main_gziiiigq1xo_6.png', 'heart_digit_main_gziiiigq1xo_7.png', 'heart_digit_main_gziiiigq1xo_8.png', 'heart_digit_main_gziiiigq1xo_9.png'],
                    type: hmUI.data_type.HEART,
                    h_space: 1,
                    align_h: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // IMG
                let widget_7 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: px(99.0165566193463),
                    y: px(174.4511720039617),
                    w: px(36.05150214592275),
                    h: px(36.05150214592275),
                    src: 'icon_tabler_heart.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Heart - TEXT Widget
                let widget_8 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(33.21579729283593),
                    y: px(192.07200396170353),
                    w: px(164.80686695278968),
                    h: px(51.50214592274678),
                    text_size: px(17.510729613733904),
                    char_space: 0,
                    color: 0xE0E0E0,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: 'BPM',
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Step - TEXT_IMG Widget
                let widget_9 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: px(282),
                    y: px(226),
                    w: px(159.656652360515),
                    h: px(51.50214592274678),
                    font_array: ['step_digit_main_6od77vkls52_0.png', 'step_digit_main_6od77vkls52_1.png', 'step_digit_main_6od77vkls52_2.png', 'step_digit_main_6od77vkls52_3.png', 'step_digit_main_6od77vkls52_4.png', 'step_digit_main_6od77vkls52_5.png', 'step_digit_main_6od77vkls52_6.png', 'step_digit_main_6od77vkls52_7.png', 'step_digit_main_6od77vkls52_8.png', 'step_digit_main_6od77vkls52_9.png'],
                    type: hmUI.data_type.STEP,
                    h_space: 1,
                    align_h: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // IMG
                let widget_10 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: px(347.126279300099),
                    y: px(172.44935622317595),
                    w: px(30.901287553648068),
                    h: px(30.901287553648068),
                    src: 'icon_custom_steps_female-shoe-white.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Step - TEXT Widget
                let widget_11 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(281.2504126774513),
                    y: px(191),
                    w: px(164.80686695278968),
                    h: px(51.50214592274678),
                    text_size: px(21.630901287553648),
                    char_space: 0,
                    color: 0xE0E0E0,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: 'Steps',
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // TIME_POINTER - TIME_POINTER Widget (Analog Clock)
                let widget_12 = hmUI.createWidget(hmUI.widget.TIME_POINTER, {
                    hour_centerX: px(240),
                    hour_centerY: px(240),
                    hour_posX: px(29),
                    hour_posY: px(142),
                  hour_path: 'hour_hand_main_6og3or9rx04.png',
                    minute_centerX: px(240),
                    minute_centerY: px(240),
                    minute_posX: px(26),
                    minute_posY: px(201),
                    minute_path: 'minute_hand_main_6og3or9rx04.png',
                    second_centerX: px(240),
                    second_centerY: px(240),
                    second_posX: px(22),
                    second_posY: px(199),
                    second_path: 'second_hand_main_6og3or9rx04.png',
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // TIME_POINTER - Hub overlay (kept above hands)
                let widget_12_cover = hmUI.createWidget(hmUI.widget.IMG, {
                    x: px(225),
                    y: px(225),
            w: px(29),
            h: px(30),
                    src: 'hand_cover_main_6og3or9rx04.png',
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                        // ========== AOD MODE BACKGROUND ==========
                let widget_aod_bg = hmUI.createWidget(hmUI.widget.IMG, {
                  x: px(0),
                  y: px(0),
                  w: px(480),
                  h: px(480),
                  src: 'background.png',
                  alpha: 255,
                  show_level: hmUI.show_level.ONLY_AOD
                });
                
                // ========== AOD MODE WIDGETS ==========

                // IMG_DATE - IMG_DATE Widget
                let widget_100 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: px(222),
                    day_startY: px(118.37200396170354),
                    day_sc_array: ['date_digit_aod_0o4qpxxqtznd_0.png', 'date_digit_aod_0o4qpxxqtznd_1.png', 'date_digit_aod_0o4qpxxqtznd_2.png', 'date_digit_aod_0o4qpxxqtznd_3.png', 'date_digit_aod_0o4qpxxqtznd_4.png', 'date_digit_aod_0o4qpxxqtznd_5.png', 'date_digit_aod_0o4qpxxqtznd_6.png', 'date_digit_aod_0o4qpxxqtznd_7.png', 'date_digit_aod_0o4qpxxqtznd_8.png', 'date_digit_aod_0o4qpxxqtznd_9.png'],
                    day_tc_array: ['date_digit_aod_0o4qpxxqtznd_0.png', 'date_digit_aod_0o4qpxxqtznd_1.png', 'date_digit_aod_0o4qpxxqtznd_2.png', 'date_digit_aod_0o4qpxxqtznd_3.png', 'date_digit_aod_0o4qpxxqtznd_4.png', 'date_digit_aod_0o4qpxxqtznd_5.png', 'date_digit_aod_0o4qpxxqtznd_6.png', 'date_digit_aod_0o4qpxxqtznd_7.png', 'date_digit_aod_0o4qpxxqtznd_8.png', 'date_digit_aod_0o4qpxxqtznd_9.png'],
                    day_en_array: ['date_digit_aod_0o4qpxxqtznd_0.png', 'date_digit_aod_0o4qpxxqtznd_1.png', 'date_digit_aod_0o4qpxxqtznd_2.png', 'date_digit_aod_0o4qpxxqtznd_3.png', 'date_digit_aod_0o4qpxxqtznd_4.png', 'date_digit_aod_0o4qpxxqtznd_5.png', 'date_digit_aod_0o4qpxxqtznd_6.png', 'date_digit_aod_0o4qpxxqtznd_7.png', 'date_digit_aod_0o4qpxxqtznd_8.png', 'date_digit_aod_0o4qpxxqtznd_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // IMG_DATE - IMG_DATE Widget
                let widget_101 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: px(223),
                    day_startY: px(118.37200396170354),
                    day_sc_array: ['date_digit_aod_biwt670bks7_0.png', 'date_digit_aod_biwt670bks7_1.png', 'date_digit_aod_biwt670bks7_2.png', 'date_digit_aod_biwt670bks7_3.png', 'date_digit_aod_biwt670bks7_4.png', 'date_digit_aod_biwt670bks7_5.png', 'date_digit_aod_biwt670bks7_6.png', 'date_digit_aod_biwt670bks7_7.png', 'date_digit_aod_biwt670bks7_8.png', 'date_digit_aod_biwt670bks7_9.png'],
                    day_tc_array: ['date_digit_aod_biwt670bks7_0.png', 'date_digit_aod_biwt670bks7_1.png', 'date_digit_aod_biwt670bks7_2.png', 'date_digit_aod_biwt670bks7_3.png', 'date_digit_aod_biwt670bks7_4.png', 'date_digit_aod_biwt670bks7_5.png', 'date_digit_aod_biwt670bks7_6.png', 'date_digit_aod_biwt670bks7_7.png', 'date_digit_aod_biwt670bks7_8.png', 'date_digit_aod_biwt670bks7_9.png'],
                    day_en_array: ['date_digit_aod_biwt670bks7_0.png', 'date_digit_aod_biwt670bks7_1.png', 'date_digit_aod_biwt670bks7_2.png', 'date_digit_aod_biwt670bks7_3.png', 'date_digit_aod_biwt670bks7_4.png', 'date_digit_aod_biwt670bks7_5.png', 'date_digit_aod_biwt670bks7_6.png', 'date_digit_aod_biwt670bks7_7.png', 'date_digit_aod_biwt670bks7_8.png', 'date_digit_aod_biwt670bks7_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // IMG_DATE - IMG_DATE Month Widget
                let widget_102 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    month_startX: px(274.21866952789696),
                    month_startY: px(130.7027731924728),
                    month_sc_array: ['month_aod_hkap2qmwbjr_0.png', 'month_aod_hkap2qmwbjr_1.png', 'month_aod_hkap2qmwbjr_2.png', 'month_aod_hkap2qmwbjr_3.png', 'month_aod_hkap2qmwbjr_4.png', 'month_aod_hkap2qmwbjr_5.png', 'month_aod_hkap2qmwbjr_6.png', 'month_aod_hkap2qmwbjr_7.png', 'month_aod_hkap2qmwbjr_8.png', 'month_aod_hkap2qmwbjr_9.png', 'month_aod_hkap2qmwbjr_10.png', 'month_aod_hkap2qmwbjr_11.png'],
                    month_tc_array: ['month_aod_hkap2qmwbjr_0.png', 'month_aod_hkap2qmwbjr_1.png', 'month_aod_hkap2qmwbjr_2.png', 'month_aod_hkap2qmwbjr_3.png', 'month_aod_hkap2qmwbjr_4.png', 'month_aod_hkap2qmwbjr_5.png', 'month_aod_hkap2qmwbjr_6.png', 'month_aod_hkap2qmwbjr_7.png', 'month_aod_hkap2qmwbjr_8.png', 'month_aod_hkap2qmwbjr_9.png', 'month_aod_hkap2qmwbjr_10.png', 'month_aod_hkap2qmwbjr_11.png'],
                    month_en_array: ['month_aod_hkap2qmwbjr_0.png', 'month_aod_hkap2qmwbjr_1.png', 'month_aod_hkap2qmwbjr_2.png', 'month_aod_hkap2qmwbjr_3.png', 'month_aod_hkap2qmwbjr_4.png', 'month_aod_hkap2qmwbjr_5.png', 'month_aod_hkap2qmwbjr_6.png', 'month_aod_hkap2qmwbjr_7.png', 'month_aod_hkap2qmwbjr_8.png', 'month_aod_hkap2qmwbjr_9.png', 'month_aod_hkap2qmwbjr_10.png', 'month_aod_hkap2qmwbjr_11.png'],
                    month_zero: 0,
                    month_space: 0,
                    month_is_character: true,
                    month_align: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // IMG_DATE - IMG_WEEK Widget
                let widget_103 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                    x: px(137.1917464509739),
                    y: px(132.93738857708814),
                    week_en: ['week_aod_0jsjisxv1nvn_0.png', 'week_aod_0jsjisxv1nvn_1.png', 'week_aod_0jsjisxv1nvn_2.png', 'week_aod_0jsjisxv1nvn_3.png', 'week_aod_0jsjisxv1nvn_4.png', 'week_aod_0jsjisxv1nvn_5.png', 'week_aod_0jsjisxv1nvn_6.png'],
                    week_sc: ['week_aod_0jsjisxv1nvn_0.png', 'week_aod_0jsjisxv1nvn_1.png', 'week_aod_0jsjisxv1nvn_2.png', 'week_aod_0jsjisxv1nvn_3.png', 'week_aod_0jsjisxv1nvn_4.png', 'week_aod_0jsjisxv1nvn_5.png', 'week_aod_0jsjisxv1nvn_6.png'],
                    week_tc: ['week_aod_0jsjisxv1nvn_0.png', 'week_aod_0jsjisxv1nvn_1.png', 'week_aod_0jsjisxv1nvn_2.png', 'week_aod_0jsjisxv1nvn_3.png', 'week_aod_0jsjisxv1nvn_4.png', 'week_aod_0jsjisxv1nvn_5.png', 'week_aod_0jsjisxv1nvn_6.png'],
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Heart - TEXT_IMG Widget
                let widget_104 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: px(68.22223506107625),
                    y: px(222.61046550016505),
                    w: px(95.79399141630901),
                    h: px(51.50214592274678),
                    font_array: ['heart_digit_aod_gziiiigq1xo_0.png', 'heart_digit_aod_gziiiigq1xo_1.png', 'heart_digit_aod_gziiiigq1xo_2.png', 'heart_digit_aod_gziiiigq1xo_3.png', 'heart_digit_aod_gziiiigq1xo_4.png', 'heart_digit_aod_gziiiigq1xo_5.png', 'heart_digit_aod_gziiiigq1xo_6.png', 'heart_digit_aod_gziiiigq1xo_7.png', 'heart_digit_aod_gziiiigq1xo_8.png', 'heart_digit_aod_gziiiigq1xo_9.png'],
                    type: hmUI.data_type.HEART,
                    h_space: 1,
                    align_h: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // IMG
                let widget_105 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: px(99.0165566193463),
                    y: px(174.4511720039617),
                    w: px(36.05150214592275),
                    h: px(36.05150214592275),
                    src: 'icon_tabler_heart.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Heart - TEXT Widget
                let widget_106 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(33.21579729283593),
                    y: px(192.07200396170353),
                    w: px(164.80686695278968),
                    h: px(51.50214592274678),
                    text_size: px(17.510729613733904),
                    char_space: 0,
                    color: 0xE0E0E0,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: 'BPM',
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Step - TEXT_IMG Widget
                let widget_107 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: px(282),
                    y: px(226),
                    w: px(159.656652360515),
                    h: px(51.50214592274678),
                    font_array: ['step_digit_aod_6od77vkls52_0.png', 'step_digit_aod_6od77vkls52_1.png', 'step_digit_aod_6od77vkls52_2.png', 'step_digit_aod_6od77vkls52_3.png', 'step_digit_aod_6od77vkls52_4.png', 'step_digit_aod_6od77vkls52_5.png', 'step_digit_aod_6od77vkls52_6.png', 'step_digit_aod_6od77vkls52_7.png', 'step_digit_aod_6od77vkls52_8.png', 'step_digit_aod_6od77vkls52_9.png'],
                    type: hmUI.data_type.STEP,
                    h_space: 1,
                    align_h: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // IMG
                let widget_108 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: px(347.126279300099),
                    y: px(172.44935622317595),
                    w: px(30.901287553648068),
                    h: px(30.901287553648068),
                    src: 'icon_custom_steps_female-shoe-white.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Step - TEXT Widget
                let widget_109 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(281.2504126774513),
                    y: px(191),
                    w: px(164.80686695278968),
                    h: px(51.50214592274678),
                    text_size: px(21.630901287553648),
                    char_space: 0,
                    color: 0xE0E0E0,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: 'Steps',
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // TIME_POINTER - TIME_POINTER Widget (Analog Clock)
                let widget_110 = hmUI.createWidget(hmUI.widget.TIME_POINTER, {
                    hour_centerX: px(240),
                    hour_centerY: px(240),
                    hour_posX: px(29),
                    hour_posY: px(142),
                  hour_path: 'hour_hand_aod_6og3or9rx04.png',
                    minute_centerX: px(240),
                    minute_centerY: px(240),
                    minute_posX: px(26),
                    minute_posY: px(201),
                    minute_path: 'minute_hand_aod_6og3or9rx04.png',
                    second_centerX: px(240),
                    second_centerY: px(240),
                    second_posX: px(22),
                    second_posY: px(199),
                    second_path: 'second_hand_aod_6og3or9rx04.png',
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // TIME_POINTER - Hub overlay (kept above hands)
                let widget_110_cover = hmUI.createWidget(hmUI.widget.IMG, {
                    x: px(225),
                    y: px(225),
            w: px(29),
            h: px(30),
                    src: 'hand_cover_aod_6og3or9rx04.png',
                    show_level: hmUI.show_level.ONLY_AOD
                });

                // Widget delegate for lifecycle management (matches working reference)
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        console.log('resume_call()');
                        let tipoSchermo = hmSetting.getScreenType();
                        if (tipoSchermo === hmSetting.screen_type.WATCHFACE) {
                            // NORMAL MODE updates
                        } else if (tipoSchermo === hmSetting.screen_type.AOD) {
                            // AOD MODE updates
                        }
                    },
                    pause_call() {
                        console.log('pause_call()');
                    }
                });
            },
            onInit() {
                logger.log('index page.js on init invoke');
            },
            build() {
                this.init_view();
                logger.log('index page.js on ready invoke');
            },
            onDestroy() {
                logger.log('index page.js on destroy invoke');
            }
        });
        ;
    })();
} catch (e) {
    console.log('Mini Program Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
    ;
}