// Zepp OS Watchface generated by AI WatchFace Creator (V2 Format)
// V2 Manifest: Full A OD support with dynamic widgets
// Compatible with Amazfit Balance 2, Balance, Active Max
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('WatchFaceEditor');
        
        // Sensor for weather and system info
        let weatherSensor = null;

        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // Initialize sensors
                try {
                    weatherSensor = hmSensor.createSensor(hmSensor.id.WEATHER);
                } catch (e) {
                    logger.log('Weather sensor init failed:', e);
                }
                
                // ========== NORMAL MODE BACKGROUND ==========
                let widget_1 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'background.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== NORMAL MODE WIDGETS ==========

                // Digital Time 13 - IMG_TIME Widget
                let widget_2 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: 140,
                    hour_startY: 240,
                    hour_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    hour_space: 0,
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: 270,
                    minute_startY: 240,
                    minute_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    minute_space: 0,
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Date 15 - IMG_DATE Widget
                let widget_3 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: 204,
                    day_startY: 213,
                    day_sc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_tc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_en_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Weekday 14 - IMG_WEEK Widget
                let widget_4 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                    x: 190,
                    y: 222,
                    week_en: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    week_sc: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    week_tc: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Arc Arc 0 - ARC_PROGRESS Widget
                let widget_5 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 240,
                    radius: 80,
                    start_angle: 135,
                    end_angle: 420,
                    color: 0xEE5A24,
                    line_width: 4,
                    type: hmUI.data_type.SPO2,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Weather Value 1 - TEXT_IMG Widget
                let widget_6 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 94,
                    w: 160,
                    h: 50,
                    font_array: ['digit_0.png', 'digit_1.png', 'digit_2.png', 'digit_3.png', 'digit_4.png', 'digit_5.png', 'digit_6.png', 'digit_7.png', 'digit_8.png', 'digit_9.png'],
                    type: hmUI.data_type.WEATHER_CURRENT,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Battery Value 3 - TEXT_IMG Widget
                let widget_7 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 138,
                    w: 160,
                    h: 50,
                    font_array: ['batt_digit_0.png', 'batt_digit_1.png', 'batt_digit_2.png', 'batt_digit_3.png', 'batt_digit_4.png', 'batt_digit_5.png', 'batt_digit_6.png', 'batt_digit_7.png', 'batt_digit_8.png', 'batt_digit_9.png'],
                    type: hmUI.data_type.BATTERY,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Steps Value 5 - TEXT_IMG Widget
                let widget_8 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 182,
                    w: 160,
                    h: 50,
                    font_array: ['step_digit_0.png', 'step_digit_1.png', 'step_digit_2.png', 'step_digit_3.png', 'step_digit_4.png', 'step_digit_5.png', 'step_digit_6.png', 'step_digit_7.png', 'step_digit_8.png', 'step_digit_9.png'],
                    type: hmUI.data_type.STEP,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Heart Rate Value 7 - TEXT_IMG Widget
                let widget_9 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 226,
                    w: 160,
                    h: 50,
                    font_array: ['heart_digit_0.png', 'heart_digit_1.png', 'heart_digit_2.png', 'heart_digit_3.png', 'heart_digit_4.png', 'heart_digit_5.png', 'heart_digit_6.png', 'heart_digit_7.png', 'heart_digit_8.png', 'heart_digit_9.png'],
                    type: hmUI.data_type.HEART,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Text Value 9 - TEXT_IMG Widget
                let widget_10 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 270,
                    w: 160,
                    h: 50,
                    font_array: ['digit_0.png', 'digit_1.png', 'digit_2.png', 'digit_3.png', 'digit_4.png', 'digit_5.png', 'digit_6.png', 'digit_7.png', 'digit_8.png', 'digit_9.png'],
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Text Value 11 - TEXT_IMG Widget
                let widget_11 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 314,
                    w: 160,
                    h: 50,
                    font_array: ['digit_0.png', 'digit_1.png', 'digit_2.png', 'digit_3.png', 'digit_4.png', 'digit_5.png', 'digit_6.png', 'digit_7.png', 'digit_8.png', 'digit_9.png'],
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Text Value 18 - TEXT_IMG Widget
                let widget_12 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 160,
                    y: 55,
                    w: 160,
                    h: 50,
                    font_array: ['digit_0.png', 'digit_1.png', 'digit_2.png', 'digit_3.png', 'digit_4.png', 'digit_5.png', 'digit_6.png', 'digit_7.png', 'digit_8.png', 'digit_9.png'],
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== AOD MODE BACKGROUND ==========
                let widget_aod_bg = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'background.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                
                // ========== AOD MODE WIDGETS ==========

                // Digital Time 13 - IMG_TIME Widget
                let widget_100 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: 140,
                    hour_startY: 240,
                    hour_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    hour_space: 0,
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: 270,
                    minute_startY: 240,
                    minute_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    minute_space: 0,
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Date 15 - IMG_DATE Widget
                let widget_101 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: 204,
                    day_startY: 213,
                    day_sc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_tc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_en_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Weekday 14 - IMG_WEEK Widget
                let widget_102 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                    x: 190,
                    y: 222,
                    week_en: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    week_sc: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    week_tc: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Arc Arc 0 - ARC_PROGRESS Widget
                let widget_103 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 240,
                    radius: 80,
                    start_angle: 135,
                    end_angle: 420,
                    color: 0xEE5A24,
                    line_width: 4,
                    type: hmUI.data_type.SPO2,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Weather Value 1 - TEXT_IMG Widget
                let widget_104 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 94,
                    w: 160,
                    h: 50,
                    font_array: ['digit_0.png', 'digit_1.png', 'digit_2.png', 'digit_3.png', 'digit_4.png', 'digit_5.png', 'digit_6.png', 'digit_7.png', 'digit_8.png', 'digit_9.png'],
                    type: hmUI.data_type.WEATHER_CURRENT,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Battery Value 3 - TEXT_IMG Widget
                let widget_105 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 138,
                    w: 160,
                    h: 50,
                    font_array: ['batt_digit_0.png', 'batt_digit_1.png', 'batt_digit_2.png', 'batt_digit_3.png', 'batt_digit_4.png', 'batt_digit_5.png', 'batt_digit_6.png', 'batt_digit_7.png', 'batt_digit_8.png', 'batt_digit_9.png'],
                    type: hmUI.data_type.BATTERY,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Steps Value 5 - TEXT_IMG Widget
                let widget_106 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 182,
                    w: 160,
                    h: 50,
                    font_array: ['step_digit_0.png', 'step_digit_1.png', 'step_digit_2.png', 'step_digit_3.png', 'step_digit_4.png', 'step_digit_5.png', 'step_digit_6.png', 'step_digit_7.png', 'step_digit_8.png', 'step_digit_9.png'],
                    type: hmUI.data_type.STEP,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Heart Rate Value 7 - TEXT_IMG Widget
                let widget_107 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 226,
                    w: 160,
                    h: 50,
                    font_array: ['heart_digit_0.png', 'heart_digit_1.png', 'heart_digit_2.png', 'heart_digit_3.png', 'heart_digit_4.png', 'heart_digit_5.png', 'heart_digit_6.png', 'heart_digit_7.png', 'heart_digit_8.png', 'heart_digit_9.png'],
                    type: hmUI.data_type.HEART,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Text Value 9 - TEXT_IMG Widget
                let widget_108 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 270,
                    w: 160,
                    h: 50,
                    font_array: ['digit_0.png', 'digit_1.png', 'digit_2.png', 'digit_3.png', 'digit_4.png', 'digit_5.png', 'digit_6.png', 'digit_7.png', 'digit_8.png', 'digit_9.png'],
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Text Value 11 - TEXT_IMG Widget
                let widget_109 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 280,
                    y: 314,
                    w: 160,
                    h: 50,
                    font_array: ['digit_0.png', 'digit_1.png', 'digit_2.png', 'digit_3.png', 'digit_4.png', 'digit_5.png', 'digit_6.png', 'digit_7.png', 'digit_8.png', 'digit_9.png'],
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Text Value 18 - TEXT_IMG Widget
                let widget_110 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 160,
                    y: 55,
                    w: 160,
                    h: 50,
                    font_array: ['digit_0.png', 'digit_1.png', 'digit_2.png', 'digit_3.png', 'digit_4.png', 'digit_5.png', 'digit_6.png', 'digit_7.png', 'digit_8.png', 'digit_9.png'],
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });

                // Widget delegate for lifecycle management (matches working reference)
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        console.log('resume_call()');
                        let tipoSchermo = hmSetting.getScreenType();
                        if (tipoSchermo === hmSetting.screen_type.WATCHFACE) {
                            // NORMAL MODE updates
                        } else if (tipoSchermo === hmSetting.screen_type.AOD) {
                            // AOD MODE updates
                        }
                    },
                    pause_call() {
                        console.log('pause_call()');
                    }
                });
            },
            onInit() {
                logger.log('index page.js on init invoke');
            },
            build() {
                this.init_view();
                logger.log('index page.js on ready invoke');
            },
            onDestroy() {
                logger.log('index page.js on destroy invoke');
            }
        });
        ;
    })();
} catch (e) {
    console.log('Mini Program Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
    ;
}