// Zepp OS Watchface generated by AI WatchFace Creator (V2 Format)
// V2 Manifest: Full A OD support with dynamic widgets
// Compatible with Amazfit Balance 2, Balance, Active Max
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('WatchFaceEditor');
        
        // Sensor for weather and system info
        let weatherSensor = null;

        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // Initialize sensors
                try {
                    weatherSensor = hmSensor.createSensor(hmSensor.id.WEATHER);
                } catch (e) {
                    logger.log('Weather sensor init failed:', e);
                }
                
                // ========== NORMAL MODE BACKGROUND ==========
                let widget_1 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: px(0),
                    y: px(0),
                    w: px(480),
                    h: px(480),
                    src: 'background.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== NORMAL MODE WIDGETS ==========

                // IMG_TIME Widget (Hours @ 40,200 | Minutes @ 58,119)
                let widget_2 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: px(40),
                    hour_startY: px(200),
                    hour_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    hour_space: 0,
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: px(58),
                    minute_startY: px(119),
                    minute_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    minute_space: 0,
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Date - IMG_DATE Widget
                let widget_3 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: px(72),
                    day_startY: px(270),
                    day_sc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_tc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_en_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Weather - TEXT_IMG Widget
                let widget_4 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: px(300),
                    y: px(120),
                    w: px(140),
                    h: px(30),
                    font_array: ['weather_0.png', 'weather_1.png', 'weather_2.png', 'weather_3.png', 'weather_4.png', 'weather_5.png', 'weather_6.png', 'weather_7.png', 'weather_8.png', 'weather_9.png'],
                    type: hmUI.data_type.WEATHER_CURRENT,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Battery - TEXT_IMG Widget
                let widget_5 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: px(300),
                    y: px(160),
                    w: px(140),
                    h: px(30),
                    font_array: ['batt_digit_0.png', 'batt_digit_1.png', 'batt_digit_2.png', 'batt_digit_3.png', 'batt_digit_4.png', 'batt_digit_5.png', 'batt_digit_6.png', 'batt_digit_7.png', 'batt_digit_8.png', 'batt_digit_9.png'],
                    type: hmUI.data_type.BATTERY,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // ⚑ 6430 - TEXT Widget
                let widget_6 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(300),
                    y: px(200),
                    w: px(140),
                    h: px(30),
                    text_size: px(18),
                    char_space: 0,
                    color: 0xffffff,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: '⚑ 6430',
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Heart Rate - TEXT_IMG Widget
                let widget_7 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: px(300),
                    y: px(240),
                    w: px(140),
                    h: px(30),
                    font_array: ['heart_digit_0.png', 'heart_digit_1.png', 'heart_digit_2.png', 'heart_digit_3.png', 'heart_digit_4.png', 'heart_digit_5.png', 'heart_digit_6.png', 'heart_digit_7.png', 'heart_digit_8.png', 'heart_digit_9.png'],
                    type: hmUI.data_type.HEART,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // ❂ LOW - TEXT Widget
                let widget_8 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(300),
                    y: px(280),
                    w: px(140),
                    h: px(30),
                    text_size: px(18),
                    char_space: 0,
                    color: 0xffffff,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: '❂ LOW',
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // XII - TEXT Widget
                let widget_9 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(220),
                    y: px(20),
                    w: px(40),
                    h: px(30),
                    text_size: px(20),
                    char_space: 0,
                    color: 0xffffff,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: 'XII',
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // TIME_POINTER - TIME_POINTER Widget (Analog Clock)
                let widget_10 = hmUI.createWidget(hmUI.widget.TIME_POINTER, {
                    hour_centerX: px(240),
                    hour_centerY: px(240),
                    hour_posX: px(11),
                    hour_posY: px(115),
                    hour_path: 'assets/hour_hand.png',
                    hour_cover_path: 'assets/hand_cover.png',
                    hour_cover_x: px(225),
                    hour_cover_y: px(225),
                    minute_centerX: px(240),
                    minute_centerY: px(240),
                    minute_posX: px(8),
                    minute_posY: px(172),
                    minute_path: 'assets/minute_hand.png',
                    second_centerX: px(240),
                    second_centerY: px(240),
                    second_posX: px(4),
                    second_posY: px(203),
                    second_path: 'assets/second_hand.png',
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== AOD MODE BACKGROUND ==========
                let widget_aod_bg = hmUI.createWidget(hmUI.widget.IMG, {
                    x: px(0),
                    y: px(0),
                    w: px(480),
                    h: px(480),
                    src: 'background.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                
                // ========== AOD MODE WIDGETS ==========

                // IMG_TIME Widget (Hours @ 40,200 | Minutes @ 58,119)
                let widget_100 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: px(40),
                    hour_startY: px(200),
                    hour_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    hour_space: 0,
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: px(58),
                    minute_startY: px(119),
                    minute_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    minute_space: 0,
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Date - IMG_DATE Widget
                let widget_101 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: px(72),
                    day_startY: px(270),
                    day_sc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_tc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_en_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Weather - TEXT_IMG Widget
                let widget_102 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: px(300),
                    y: px(120),
                    w: px(140),
                    h: px(30),
                    font_array: ['weather_0.png', 'weather_1.png', 'weather_2.png', 'weather_3.png', 'weather_4.png', 'weather_5.png', 'weather_6.png', 'weather_7.png', 'weather_8.png', 'weather_9.png'],
                    type: hmUI.data_type.WEATHER_CURRENT,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Battery - TEXT_IMG Widget
                let widget_103 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: px(300),
                    y: px(160),
                    w: px(140),
                    h: px(30),
                    font_array: ['batt_digit_0.png', 'batt_digit_1.png', 'batt_digit_2.png', 'batt_digit_3.png', 'batt_digit_4.png', 'batt_digit_5.png', 'batt_digit_6.png', 'batt_digit_7.png', 'batt_digit_8.png', 'batt_digit_9.png'],
                    type: hmUI.data_type.BATTERY,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // ⚑ 6430 - TEXT Widget
                let widget_104 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(300),
                    y: px(200),
                    w: px(140),
                    h: px(30),
                    text_size: px(18),
                    char_space: 0,
                    color: 0xffffff,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: '⚑ 6430',
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Heart Rate - TEXT_IMG Widget
                let widget_105 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: px(300),
                    y: px(240),
                    w: px(140),
                    h: px(30),
                    font_array: ['heart_digit_0.png', 'heart_digit_1.png', 'heart_digit_2.png', 'heart_digit_3.png', 'heart_digit_4.png', 'heart_digit_5.png', 'heart_digit_6.png', 'heart_digit_7.png', 'heart_digit_8.png', 'heart_digit_9.png'],
                    type: hmUI.data_type.HEART,
                    h_space: 1,
                    align_h: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // ❂ LOW - TEXT Widget
                let widget_106 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(300),
                    y: px(280),
                    w: px(140),
                    h: px(30),
                    text_size: px(18),
                    char_space: 0,
                    color: 0xffffff,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: '❂ LOW',
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // XII - TEXT Widget
                let widget_107 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(220),
                    y: px(20),
                    w: px(40),
                    h: px(30),
                    text_size: px(20),
                    char_space: 0,
                    color: 0xffffff,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: 'XII',
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // TIME_POINTER - TIME_POINTER Widget (Analog Clock)
                let widget_108 = hmUI.createWidget(hmUI.widget.TIME_POINTER, {
                    hour_centerX: px(240),
                    hour_centerY: px(240),
                    hour_posX: px(11),
                    hour_posY: px(115),
                    hour_path: 'assets/hour_hand.png',
                    hour_cover_path: 'assets/hand_cover.png',
                    hour_cover_x: px(225),
                    hour_cover_y: px(225),
                    minute_centerX: px(240),
                    minute_centerY: px(240),
                    minute_posX: px(8),
                    minute_posY: px(172),
                    minute_path: 'assets/minute_hand.png',
                    second_centerX: px(240),
                    second_centerY: px(240),
                    second_posX: px(4),
                    second_posY: px(203),
                    second_path: 'assets/second_hand.png',
                    show_level: hmUI.show_level.ONLY_AOD
                });

                // Widget delegate for lifecycle management (matches working reference)
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        console.log('resume_call()');
                        let tipoSchermo = hmSetting.getScreenType();
                        if (tipoSchermo === hmSetting.screen_type.WATCHFACE) {
                            // NORMAL MODE updates
                        } else if (tipoSchermo === hmSetting.screen_type.AOD) {
                            // AOD MODE updates
                        }
                    },
                    pause_call() {
                        console.log('pause_call()');
                    }
                });
            },
            onInit() {
                logger.log('index page.js on init invoke');
            },
            build() {
                this.init_view();
                logger.log('index page.js on ready invoke');
            },
            onDestroy() {
                logger.log('index page.js on destroy invoke');
            }
        });
        ;
    })();
} catch (e) {
    console.log('Mini Program Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
    ;
}