import { useEffect, useMemo, useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { useStoreReadModel } from '@/context/StoreReadModelContext';
import { compatibleDevices, modelSkus, resolveLegacyDesignModel, skuOffer, skuPackages } from '@/lib/storeReadModel';

export function DesignModelPage() {
  const { slug } = useParams(); const { data, loading, error } = useStoreReadModel();
  const model = data?.designModels.find((item) => item.slug === slug || item.id === slug) ?? null;
  const skus = useMemo(() => data && model ? modelSkus(data, model.id) : [], [data, model]);
  const [skuId, setSkuId] = useState(''); const [mode, setMode] = useState<'MAIN' | 'AOD'>('MAIN');
  useEffect(() => { if (!skus.some((item) => item.id === skuId)) setSkuId(skus[0]?.id ?? ''); }, [skus, skuId]);
  if (loading) return <Status text="Loading design…" />; if (error || !data) return <Status text={error ?? 'Store unavailable'} />; if (!model) return <Status text="Design Model not found." />;
  const sku = skus.find((item) => item.id === skuId) ?? skus[0]; if (!sku) return <Status text="No sellable edition is currently available." />;
  const offer = skuOffer(data, sku.id); const packages = skuPackages(data, sku.id); const media = packages[0]; const preview = mode === 'AOD' ? media?.aodPreviewPath : media?.mainPreviewPath; const devices = compatibleDevices(data, sku.id); const collection = data.collections.find((item) => item.id === model.collectionId);
  return <main className="min-h-screen vault-shell"><div className="mx-auto max-w-6xl px-4 py-8"><nav className="mb-6 text-xs text-[#8e96a3]"><Link to="/">Browse</Link>{collection && <> / <Link to={`/collection/${collection.slug || collection.id}`}>{collection.name}</Link></>} / <span className="text-white">{model.name}</span></nav><div className="grid gap-10 md:grid-cols-2"><section><div className="aspect-square overflow-hidden rounded-2xl border border-[#303744] bg-[#171b23]">{preview ? <img src={preview} alt={`${sku.canonicalName} ${mode} preview`} className="h-full w-full object-contain" /> : <div className="grid h-full place-items-center text-6xl text-[#657083]">⌚</div>}</div><div className="mt-3 grid grid-cols-2 gap-2" aria-label="Preview mode">{(['MAIN', 'AOD'] as const).map((item) => <button key={item} aria-pressed={mode === item} onClick={() => setMode(item)} className={`rounded-lg border px-3 py-2 text-sm ${mode === item ? 'border-[#c7a86f] text-[#e8d2a8]' : 'border-[#343b48] text-[#9da6b5]'}`}>{item === 'MAIN' ? 'Main display' : 'Always-on display'}</button>)}</div></section><section className="space-y-6"><div><p className="vault-micro">Finished FlowVault timepiece</p><h1 className="mt-2 text-4xl font-light text-white">{model.name}</h1><p className="mt-3 text-[#9da6b5]">{model.designStory || model.description || 'A complete watch design whose color and widget choices are presented as selectable editions.'}</p></div><fieldset><legend className="mb-2 text-xs uppercase tracking-wider text-[#8e96a3]">Color / Material and Edition</legend><div className="grid gap-2">{skus.map((item) => <button key={item.id} onClick={() => setSkuId(item.id)} aria-pressed={sku.id === item.id} className={`rounded-xl border p-3 text-left ${sku.id === item.id ? 'border-[#c7a86f] bg-[#c7a86f]/10' : 'border-[#343b48]'}`}><span className="text-white">{item.variant.name}</span>{item.edition?.name && <span className="text-[#9da6b5]"> — {item.edition.name}</span>}{item.variant.material && <span className="block text-xs text-[#788394]">{item.variant.material}</span>}</button>)}</div></fieldset>{offer && <div><p className="text-2xl text-[#e8d2a8]">${(offer.campaignPrice ?? offer.regularPrice).toFixed(2)}</p>{offer.campaignPrice != null && <p className="text-sm text-[#808a99] line-through">${offer.regularPrice.toFixed(2)}</p>}<Link to={`/buy/${sku.id}`} className="mt-3 block rounded-xl bg-[#bc9456] px-4 py-3 text-center font-semibold text-[#17120a]">Choose this finished timepiece</Link></div>}<div><p className="mb-2 text-xs uppercase tracking-wider text-[#8e96a3]">Compatible watches</p><div className="flex flex-wrap gap-2">{devices.map((device) => <Link key={device.id} to={`/device/${device.id}`} className="rounded-full border border-[#343b48] px-2.5 py-1 text-xs text-[#aeb6c3]">{device.name}</Link>)}</div><p className="mt-2 text-xs text-[#737d8c]">The correct technical package is selected for your device after purchase.</p></div></section></div></div></main>;
}

export function LegacyFaceResolver() { const { id } = useParams(); const { data, loading } = useStoreReadModel(); if (loading) return <Status text="Resolving watchface…" />; const model = data && id ? resolveLegacyDesignModel(data, id) : null; return model ? <Navigate to={`/design/${model.slug || model.id}`} replace /> : <Navigate to={`/legacy-face/${id ?? ''}`} replace />; }
function Status({ text }: { text: string }) { return <div className="min-h-screen grid place-items-center text-[#8e96a3]">{text}</div>; }
